# Generated by Django 4.1.7 on 2023-04-05 02:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Referencia', models.CharField(max_length=200)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=300)),
                ('PrecioSinImpuestos', models.FloatField()),
                ('ImpuestoAplicable', models.FloatField()),
                ('FechaCreacion', models.DateField(default=datetime.datetime(2023, 4, 4, 21, 10, 4, 331018))),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PrecioTotalSinImpuestos', models.FloatField(blank=True)),
                ('PrecioTotalConImpuestos', models.FloatField(blank=True)),
                ('FechaCreacion', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoArticulo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTestApp.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTestApp.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='articulos',
            field=models.ManyToManyField(through='ApiTestApp.PedidoArticulo', to='ApiTestApp.articulo'),
        ),
    ]
