# Generated by Django 4.1.7 on 2023-03-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('ArticuloId', models.AutoField(primary_key=True, serialize=False)),
                ('ArticuloReferencia', models.CharField(max_length=200)),
                ('ArticuloNombre', models.CharField(max_length=100)),
                ('ArticuloDescripcion', models.CharField(max_length=300)),
                ('ArticuloPrecioSinImpuestos', models.FloatField()),
                ('ArticuloImpuestoAplicable', models.FloatField()),
                ('ArticuloFechaCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTestApp.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('PedidoId', models.AutoField(primary_key=True, serialize=False)),
                ('PedidoPrecioTotalSinImpuestos', models.FloatField()),
                ('PedidoPrecioTotalConImpuestos', models.FloatField()),
                ('PedidoFechaCreacion', models.DateField()),
                ('articulos', models.ManyToManyField(through='ApiTestApp.ArticuloPedido', to='ApiTestApp.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTestApp.pedido'),
        ),
    ]
