# Generated by Django 4.1.7 on 2023-03-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopedido',
            name='referencia',
            field=models.CharField(default='Vacio', max_length=500),
        ),
    ]
