# Generated by Django 4.1.7 on 2023-03-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTestApp', '0002_articulopedido_referencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='ArticuloDescripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='ArticuloFechaCreacion',
            new_name='FechaCreacion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='ArticuloId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='ArticuloImpuestoAplicable',
            new_name='ImpuestoAplicable',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='ArticuloNombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='ArticuloPrecioSinImpuestos',
            new_name='PrecioSinImpuestos',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='ArticuloReferencia',
            new_name='Referencia',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='PedidoFechaCreacion',
            new_name='FechaCreacion',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='PedidoId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='PedidoPrecioTotalConImpuestos',
            new_name='PrecioTotalConImpuestos',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='PedidoPrecioTotalSinImpuestos',
            new_name='PrecioTotalSinImpuestos',
        ),
        migrations.AlterField(
            model_name='articulopedido',
            name='referencia',
            field=models.CharField(default='Sin referencia', max_length=500),
        ),
    ]
